/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.1
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

export type { NativeAssetContractAbi } from './NativeAssetContractAbi';
export type { CounterAbi } from './CounterAbi';

export { NativeAssetContractAbi__factory } from './factories/NativeAssetContractAbi__factory';
export { CounterAbi__factory } from './factories/CounterAbi__factory';
